destination: ./_site
baseurl: ""  
url: "https://robynn-corveleyn.github.io"  

title: "Robynn Corveleyn"
email: "robynn.corveleyn@uclouvain.be"

description: "Academic homepage of Robynn Corveleyn, PhD student at UCLouvain."
plugins:
  - jekyll-sitemap
default_layout: default

markdown: kramdown

